Ensure system encoding is declared as UTF-8
Fixes:

    Unhandled error:
    Traceback (most recent call last):
    File "/opt/cornac/lib64/python3.6/site-packages/cornac/cli.py", line 259, in entrypoint
    exit(root())
    File "/opt/cornac/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
    File "/opt/cornac/lib64/python3.6/site-packages/cornac/cli.py", line 47, in main
    return super().main(*a, **kw)
    File "/opt/cornac/lib64/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
    File "/opt/cornac/lib64/python3.6/site-packages/click/core.py", line 696, in main
    _verify_python3_env()
    File "/opt/cornac/lib64/python3.6/site-packages/click/_unicodefun.py", line 124, in _verify_python3_env
    ' mitigation steps.' + extra
    RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding fo
    This system lists a couple of UTF-8 supporting locales that
    you can pick from.  The following suitable locales were
    discovered: aa_DJ.utf8, aa_ER.utf8, aa_ET.utf8, af_ZA.utf8, am_ET.utf8, an_ES.utf8, ar_AE.utf8, ar_BH.utf8,
    Please report at https://github.com/dalibo/cornac/issues/new with full log.

diff --git a/service/cornac/files/cornac-setup b/service/cornac/files/cornac-setup
--- a/service/cornac/files/cornac-setup
+++ b/service/cornac/files/cornac-setup
@@ -102,6 +102,10 @@ set -x
 # Move to datadir so that other files are in current directory.
 cd $(readlink -m ${BASH_SOURCE[0]}/..)
 
+if ! locale -a | grep -q en_US.utf8 ; then
+	fatal "Cornac requires missing en_US.utf8 locale."
+fi
+
 mkdir -p /etc/opt/cornac
 
 if ! domain=$(guess_domain) ; then
